-- routine_blueprints: reusable routine templates (admin layer)
create table if not exists public.routine_blueprints (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  primary_goal text,
  secondary_goal text,
  source_routine_id uuid references public.routines(id) on delete set null,
  created_by uuid not null references public.profiles(id) on delete cascade,
  created_at timestamp with time zone not null default timezone('utc', now()),
  updated_at timestamp with time zone not null default timezone('utc', now())
);

create index if not exists routine_blueprints_created_by_idx
  on public.routine_blueprints(created_by);

-- routine_blueprint_details: exercise rows for each blueprint
create table if not exists public.routine_blueprint_details (
  id bigint generated by default as identity primary key,
  blueprint_id uuid not null references public.routine_blueprints(id) on delete cascade,
  day_of_week integer not null,
  exercise_id bigint references public.exercises(id) on delete set null,
  exercise_order integer,
  block_type text not null default 'strength',
  sets integer,
  reps text,
  rest_seconds integer,
  duration_minutes integer,
  target_rir numeric(3,1),
  notes text,
  exercise_name_snapshot text,
  check (block_type in ('warmup', 'strength', 'accessory', 'cardio', 'mobility'))
);

create index if not exists routine_blueprint_details_blueprint_idx
  on public.routine_blueprint_details(blueprint_id);
create index if not exists routine_blueprint_details_day_idx
  on public.routine_blueprint_details(blueprint_id, day_of_week);

-- routine_blueprint_assignments: which users received which blueprint
create table if not exists public.routine_blueprint_assignments (
  id uuid primary key default gen_random_uuid(),
  blueprint_id uuid not null references public.routine_blueprints(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  assigned_routine_id uuid not null references public.routines(id) on delete cascade,
  assigned_by uuid not null references public.profiles(id) on delete cascade,
  assigned_at timestamp with time zone not null default timezone('utc', now()),
  unique (assigned_routine_id)
);

create index if not exists routine_blueprint_assignments_blueprint_idx
  on public.routine_blueprint_assignments(blueprint_id);
create index if not exists routine_blueprint_assignments_user_idx
  on public.routine_blueprint_assignments(user_id);

-- RLS: blueprints and details visible to admin/trainer
alter table public.routine_blueprints enable row level security;
alter table public.routine_blueprint_details enable row level security;
alter table public.routine_blueprint_assignments enable row level security;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public'
      and tablename = 'routine_blueprints'
      and policyname = 'routine_blueprints_admin_trainer_all'
  ) then
    create policy routine_blueprints_admin_trainer_all
      on public.routine_blueprints
      for all
      using (
        exists (
          select 1 from public.profiles p
          where p.id = auth.uid()
            and p.role in ('admin', 'trainer')
        )
      )
      with check (
        exists (
          select 1 from public.profiles p
          where p.id = auth.uid()
            and p.role in ('admin', 'trainer')
        )
      );
  end if;
end $$;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public'
      and tablename = 'routine_blueprint_details'
      and policyname = 'routine_blueprint_details_admin_trainer_all'
  ) then
    create policy routine_blueprint_details_admin_trainer_all
      on public.routine_blueprint_details
      for all
      using (
        exists (
          select 1 from public.profiles p
          where p.id = auth.uid()
            and p.role in ('admin', 'trainer')
        )
      )
      with check (
        exists (
          select 1 from public.profiles p
          where p.id = auth.uid()
            and p.role in ('admin', 'trainer')
        )
      );
  end if;
end $$;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public'
      and tablename = 'routine_blueprint_assignments'
      and policyname = 'routine_blueprint_assignments_admin_trainer_all'
  ) then
    create policy routine_blueprint_assignments_admin_trainer_all
      on public.routine_blueprint_assignments
      for all
      using (
        exists (
          select 1 from public.profiles p
          where p.id = auth.uid()
            and p.role in ('admin', 'trainer')
        )
      )
      with check (
        exists (
          select 1 from public.profiles p
          where p.id = auth.uid()
            and p.role in ('admin', 'trainer')
        )
      );
  end if;
end $$;

-- backfill: create a blueprint from every active/draft routine
do $$
declare
  r record;
  bp_id uuid;
begin
  for r in
    select *
    from public.routines
    where status in ('active', 'draft')
      and user_id is not null
  loop
    insert into public.routine_blueprints (
      id, name, primary_goal, secondary_goal,
      source_routine_id, created_by, created_at, updated_at
    ) values (
      gen_random_uuid(),
      coalesce(r.name, 'Rutina'),
      r.primary_goal,
      r.secondary_goal,
      r.id,
      coalesce(r.created_by, r.user_id),
      coalesce(r.reviewed_at, now()),
      coalesce(r.reviewed_at, now())
    )
    returning id into bp_id;

    insert into public.routine_blueprint_details (
      blueprint_id, day_of_week, exercise_id, exercise_order,
      block_type, sets, reps, rest_seconds, duration_minutes,
      target_rir, notes, exercise_name_snapshot
    )
    select
      bp_id, rd.day_of_week, rd.exercise_id, rd.exercise_order,
      rd.block_type, rd.sets, rd.reps, rd.rest_seconds,
      rd.duration_minutes, rd.target_rir, rd.notes,
      rd.exercise_name_snapshot
    from public.routine_details rd
    where rd.routine_id = r.id
    order by rd.day_of_week, rd.exercise_order;

    insert into public.routine_blueprint_assignments (
      id, blueprint_id, user_id, assigned_routine_id, assigned_by, assigned_at
    ) values (
      gen_random_uuid(),
      bp_id,
      r.user_id,
      r.id,
      coalesce(r.created_by, r.user_id),
      coalesce(r.reviewed_at, now())
    );
  end loop;
end $$;
